# Generated by Django 4.2.2 on 2023-08-01 10:37

from django.db import migrations, models
import django.db.models.deletion
import inventory.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': '2 Category',
                'verbose_name_plural': '2 Categories',
            },
        ),
        migrations.CreateModel(
            name='CircleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_image', models.ImageField(blank=True, help_text='Please upload an image with dimensions 1080x1080.', null=True, upload_to=inventory.models.get_upload_path)),
                ('alt_text', models.CharField(help_text='Please provide the alternate text to display', max_length=100)),
                ('circle_category_name', models.CharField(help_text='This is the text that appears below the Circle', max_length=50)),
            ],
            options={
                'verbose_name': '4 Circle Category',
                'verbose_name_plural': '4 Circle Categories',
            },
        ),
        migrations.CreateModel(
            name='LeftImageContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=inventory.models.get_upload_path)),
                ('alternate_text', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '8 Left Image Container',
                'verbose_name_plural': '8 Left Image Container',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.models.get_upload_path)),
                ('alternate_text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '5 Main Banner',
                'verbose_name_plural': '5 Main Banners',
            },
        ),
        migrations.CreateModel(
            name='MobileBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.models.get_upload_path)),
                ('alternate_text', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '7 MobileBanner',
                'verbose_name_plural': '7 MobileBanners',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('product_main_image', models.ImageField(upload_to='')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('best_seller', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('number_reviews', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.CharField(default='100', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '12 Product',
                'verbose_name_plural': '12 Products',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('text', 'Text'), ('date_picker', 'Date Picker'), ('image', 'Image'), ('multiple_images', 'Multiple Images')], max_length=100)),
                ('has_color', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagsmain', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='RightImageContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=inventory.models.get_upload_path)),
                ('alternate_text', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '10 Right Image Container',
                'verbose_name_plural': '10 Right Image Container',
            },
        ),
        migrations.CreateModel(
            name='SubBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.models.get_upload_path)),
                ('alternate_text', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '6 SubBanner',
                'verbose_name_plural': '6 SubBanners',
            },
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please write the name in ALL CAPITALS', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, help_text='Please upload an image with dimensions 1080x1080.', null=True, upload_to=inventory.models.get_upload_path)),
            ],
            options={
                'verbose_name': '1 Super Category',
                'verbose_name_plural': '1 Super Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(blank=True, to='inventory.category')),
                ('super_categories', models.ManyToManyField(to='inventory.supercategory')),
            ],
            options={
                'verbose_name': '3 Sub Category',
                'verbose_name_plural': '3 Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='RightContainerSubImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.models.get_upload_path)),
                ('alternate_text', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rightimagecontainer')),
            ],
            options={
                'verbose_name': '11 Right Container Sub Image',
                'verbose_name_plural': '11 Right Container Sub Images',
            },
        ),
        migrations.CreateModel(
            name='ProductTagEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_tagname', models.CharField(max_length=100)),
                ('custom_choice', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='inventory.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.producttag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_image1', models.ImageField(blank=True, upload_to=inventory.models.ProductSubImage.get_upload_path)),
                ('sub_image2', models.ImageField(blank=True, upload_to=inventory.models.ProductSubImage.get_upload_path)),
                ('sub_image3', models.ImageField(blank=True, upload_to=inventory.models.ProductSubImage.get_upload_path)),
                ('sub_image4', models.ImageField(blank=True, upload_to=inventory.models.ProductSubImage.get_upload_path)),
                ('sub_image5', models.ImageField(blank=True, upload_to=inventory.models.ProductSubImage.get_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=200)),
                ('text1', models.TextField(blank=True)),
                ('subheadingd1', models.CharField(blank=True, max_length=200)),
                ('subheadingd1_text', models.TextField(blank=True)),
                ('subheadingd2', models.CharField(blank=True, max_length=200)),
                ('subheadingd2_text', models.TextField(blank=True)),
                ('heading2', models.CharField(blank=True, max_length=200)),
                ('subheadingdi1', models.CharField(blank=True, max_length=200)),
                ('subheadingdi1_text', models.TextField(blank=True)),
                ('heading3', models.CharField(blank=True, max_length=200)),
                ('subheadingi1', models.CharField(blank=True, max_length=200)),
                ('subheadingi1_text', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='SubCategory',
            field=models.ManyToManyField(blank=True, to='inventory.subcategory'),
        ),
        migrations.CreateModel(
            name='LeftContainerSubImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=inventory.models.get_upload_path)),
                ('alternate_text', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.leftimagecontainer')),
            ],
            options={
                'verbose_name': '9 Left Container Sub Image',
                'verbose_name_plural': '9 Left Container Sub Images',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ManyToManyField(blank=True, to='inventory.supercategory'),
        ),
    ]
