# Generated by Django 4.2.2 on 2023-07-06 05:35

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Caterogies',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=64)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('actual_price', models.IntegerField(blank=True)),
                ('discount_price', models.IntegerField(blank=True)),
                ('offer', models.CharField(blank=True, max_length=500)),
                ('images', models.ImageField(blank=True, upload_to=inventory.models.get_image_upload_path)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
