# Generated by Django 4.2.2 on 2023-07-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circlecategory',
            options={'verbose_name': '4 Circle Category', 'verbose_name_plural': '4 Circle Categories'},
        ),
        migrations.AlterModelOptions(
            name='leftcontainersubimages',
            options={'verbose_name': '9 Left Container Sub Image', 'verbose_name_plural': '9 Left Container Sub Images'},
        ),
        migrations.AlterModelOptions(
            name='leftimagecontainer',
            options={'verbose_name': '8 Left Image Container', 'verbose_name_plural': '8 Left Image Container'},
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': '5 Main Banner', 'verbose_name_plural': '5 Main Banners'},
        ),
        migrations.AlterModelOptions(
            name='mobilebanner',
            options={'verbose_name': '7 MobileBanner', 'verbose_name_plural': '7 MobileBanners'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '12 Product', 'verbose_name_plural': '12 Products'},
        ),
        migrations.AlterModelOptions(
            name='rightcontainersubimages',
            options={'verbose_name': '11 Right Container Sub Image', 'verbose_name_plural': '11 Right Container Sub Images'},
        ),
        migrations.AlterModelOptions(
            name='rightimagecontainer',
            options={'verbose_name': '10 Right Image Container', 'verbose_name_plural': '10 Right Image Container'},
        ),
        migrations.AlterModelOptions(
            name='subbanner',
            options={'verbose_name': '6 SubBanner', 'verbose_name_plural': '6 SubBanners'},
        ),
        migrations.RenameField(
            model_name='supercategory',
            old_name='image',
            new_name='super_image',
        ),
        migrations.AlterField(
            model_name='circlecategory',
            name='circle_image',
            field=models.ImageField(blank=True, help_text='Please upload an image with dimensions 1080x1080.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='leftcontainersubimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='leftimagecontainer',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mobilebanner',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='rightimagecontainer',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='subbanner',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
