# Generated by Django 4.2.2 on 2023-08-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='has_color',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='tag',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('date_picker', 'Date Picker'), ('image', 'Image'), ('multiple_images', 'Multiple Images')], max_length=100),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='tagname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
