# Generated by Django 4.2.2 on 2023-07-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_circlecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supercategory',
            old_name='super_image',
            new_name='image',
        ),
    ]
