# Generated by Django 4.2.2 on 2023-07-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_category_super_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='SubCategory',
        ),
    ]
