# Generated by Django 4.2.2 on 2023-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_image_url', models.CharField(max_length=200)),
                ('alt_text', models.CharField(max_length=100)),
                ('circle_category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
