# Generated by Django 4.2.2 on 2023-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_circlecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circlecategory',
            name='circle_image_url',
        ),
        migrations.AddField(
            model_name='circlecategory',
            name='circle_image',
            field=models.ImageField(blank=True, help_text='Please write the name in ALL CAPITALS', null=True, upload_to='super_category/'),
        ),
        migrations.AlterField(
            model_name='circlecategory',
            name='alt_text',
            field=models.CharField(help_text='Please provide the alternate tex to display', max_length=100),
        ),
        migrations.AlterField(
            model_name='circlecategory',
            name='circle_category_name',
            field=models.CharField(help_text='This is the text that appears below the Circle', max_length=50),
        ),
    ]
