# Generated by Django 4.2.2 on 2023-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_circlecategory_circle_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('alternate_text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='circlecategory',
            options={'verbose_name': 'Circle Category', 'verbose_name_plural': 'Circle Categories'},
        ),
        migrations.AlterField(
            model_name='circlecategory',
            name='circle_image',
            field=models.ImageField(blank=True, help_text='Please upload an image with dimensions 1080x1080.', null=True, upload_to='circle_category/'),
        ),
    ]
