# Generated by Django 4.2.2 on 2023-07-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_mainbanner_alter_circlecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftImageContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Left_Image_Container/Side_Banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Left Image Container',
                'verbose_name_plural': 'Left Image Container',
            },
        ),
        migrations.CreateModel(
            name='RightImageContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Right_Image_Container/Side_Banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Right Image Container',
                'verbose_name_plural': 'Right Image Container',
            },
        ),
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'verbose_name': 'Main Banner', 'verbose_name_plural': 'Main Banners'},
        ),
        migrations.CreateModel(
            name='RightContainerSubImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Right_Image_Container/Sub_Images/')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rightimagecontainer')),
            ],
            options={
                'verbose_name': 'Right Container Sub Image',
                'verbose_name_plural': 'Right Container Sub Images',
            },
        ),
        migrations.CreateModel(
            name='LeftContainerSubImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Left_Image_Container/Sub_Images/')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.leftimagecontainer')),
            ],
            options={
                'verbose_name': 'Left Container Sub Image',
                'verbose_name_plural': 'Left Container Sub Images',
            },
        ),
    ]
