# Generated by Django 4.2.2 on 2023-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_leftcontainersubimages_alternate_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='super_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image1',
            field=models.ImageField(blank=True, upload_to='Product/SubImages/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image2',
            field=models.ImageField(blank=True, upload_to='Product/SubImages/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image3',
            field=models.ImageField(blank=True, upload_to='Product/SubImages/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image4',
            field=models.ImageField(blank=True, upload_to='Product/SubImages/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image5',
            field=models.ImageField(blank=True, upload_to='Product/SubImages/'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='SubCategory',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.subcategory'),
        ),
    ]
