# Generated by Django 4.2.2 on 2023-07-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_product_category_remove_product_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_main_image',
            field=models.ImageField(upload_to='Product/MainImage/'),
        ),
    ]
