# Generated by Django 4.2.2 on 2023-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default='100', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SubCategory',
            field=models.ManyToManyField(blank=True, to='inventory.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_reviews',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
